//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class phoneTable
    {
        public int id { get; set; }
        public string Number { get; set; }
        public string SimCompany { get; set; }
        public int ContactID { get; set; }
    
        public virtual phoneTable phoneTable1 { get; set; }
        public virtual phoneTable phoneTable2 { get; set; }
    }
}
